### ISSUE TITLE
Distribution Lists issues

### ISSUE THREAD

**Issue by umairmalik2410** [coax/hmailserver-webadmin#16]
1. The Enabled button is always 'unchecked' which doesn't show the exact 'current' situation.

2. When you click on the Add Button and add an email address, it should revert back to the original distribution list that you were editing. Or the editing can be done in-line so that there are fewer page loads.

**Comment by coax** [comment]
1. Fixed
2. Due to script logic, this cannot be changed

**Comment by umairmalik2410** [comment]
That was quick. thanks!

**Comment by umairmalik2410** [comment]
Adding on to my second point, is it possible to have a 'save and return' button after entering the email address. 

Currently when you save the email address, the only way to go back the 'distribution list' is by clicking on the cancel button 2 times. Same is the case with trying to go back to the distribution list main page, you have to click cancel multiple times in order to go back to the page that lists all the different distribution lists you've created.

**Comment by coax** [comment]
I appreciate the feedback, but return address is not passed in query and buttons are generated from uniform function in functions.php (cancel button is simple javascript "browser back"). I don't want to mess around with that because it requires heavy, manual modification on all files. The original files didn't have any "cancel" button.

**Comment by umairmalik2410** [comment]
Thank you for looking into this!
